### ISSUE TITLE
Why is pzip compression larger than tar command compression?

### ISSUE THREAD

**Issue by Nuclear6** [ybirader/pzip#6]
Project is great, compression speed is fast, but I found that compared to tar command compression, pzip compression package is larger. Why is that?

**Comment by ybirader** [comment]
`tar` is different to `zip`.

Technically, `tar` is an uncompressed archive format. You can compress a `tar` file, e.g. by using `gzip` but the size of the resulting compressed file will be related to what type of compression you use.

In addition, a compressed tar file will usually be smaller than a corresponding zip archive for a number of reasons.

- zip stores additional metadata e.g. file attributes, directory table.
- zip compresses each file individually, whereas tar archives all files first- then the entire archive is compressed so you usually get better compression.


Hope that helps!
